/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.awt.CardLayout;
import panels.ConfigureDBPanel;
import panels.ConfigurePortPanel;
import panels.ConfigureServerPanel;

/**
 *
 * @author Uros
 */
public class ServerForm extends javax.swing.JFrame {

    private final CardLayout cardLayout;
    private final ConfigureServerPanel configureServerPanel;
    private final ConfigureDBPanel configureDBPanel;
    private final ConfigurePortPanel configurePortPanel;

    /**
     * Creates new form ServerForm
     */
    public ServerForm() {
        initComponents();
        setVisible(true);
        this.cardLayout = new CardLayout();
        this.configureServerPanel = new ConfigureServerPanel();
        this.configureDBPanel = new ConfigureDBPanel();
        this.configurePortPanel = new ConfigurePortPanel();
        pnlMain.setLayout(cardLayout);
        pnlMain.add(configureServerPanel, "configureServerPanel");
        pnlMain.add(configureDBPanel, "configureDBPanel");
        pnlMain.add(configurePortPanel, "configurePortPanel");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemServer = new javax.swing.JMenuItem();
        itemDB = new javax.swing.JMenuItem();
        itemPort = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server form");
        setResizable(false);

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        jMenu1.setText("Meni");

        itemServer.setText("Konfiguracija servera");
        itemServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemServerActionPerformed(evt);
            }
        });
        jMenu1.add(itemServer);

        itemDB.setText("Konfiguracija baze");
        itemDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDBActionPerformed(evt);
            }
        });
        jMenu1.add(itemDB);

        itemPort.setText("Konfiguracija porta");
        itemPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPortActionPerformed(evt);
            }
        });
        jMenu1.add(itemPort);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemServerActionPerformed
        cardLayout.show(pnlMain, "configureServerPanel");
    }//GEN-LAST:event_itemServerActionPerformed

    private void itemDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDBActionPerformed
        cardLayout.show(pnlMain, "configureDBPanel");
    }//GEN-LAST:event_itemDBActionPerformed

    private void itemPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPortActionPerformed
        cardLayout.show(pnlMain, "configurePortPanel");
    }//GEN-LAST:event_itemPortActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemDB;
    private javax.swing.JMenuItem itemPort;
    private javax.swing.JMenuItem itemServer;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
